install:
  script:
    - mysql -uroot -e 'drop database test_mysql;'
    - mysql -uroot -e 'create database test_mysql;'
    - mkdir bin
    - cd bin
    - cmake ../ -DWITH_WARNINGS=1 -DTOOLS=1 -DCMAKE_BUILD_TYPE=Release
    - cd ..
    - chmod +x contrib/check_updates.sh
    - mysql -uroot auth < sql/base/auth_database.sql
    - mysql -uroot  characters < sql/base/characters_database.sql
    - mysql -uroot world < sql/base/dev/world_database.sql
 
    - cd bin
    - make -j 15 -k