services:
  - mysql:latest

variables:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

before_script:
  - apt-get -yqq update
  - apt-get -yqq install build-essential libtool make cmake openssl mysql-server mysql-client
  - apt-get -yqq install libssl-dev default-libmysqlclient-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev libzmq3-dev libboost-all-dev

install:
  script:
    - mysql -uroot -e 'create database test_mysql;'
    - mkdir bin
    - cd bin
    - cmake ../ -DWITH_WARNINGS=1 -DTOOLS=1 -DSCRIPTS=1 -DCMAKE_BUILD_TYPE=Release
    - make -j 10 -k