services:
  - mysql:latest

variables:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

before_script:
  - apt-get update
  - apt-get install git clang cmake make gcc g++ libmysqlclient-dev libssl-dev libbz2-dev libreadline-dev libncurses-dev libboost-all-dev mysql-server p7zip

install:
  script:
    - mkdir bin
    - cd bin
    - cmake ../ -DWITH_WARNINGS=1 -DTOOLS=1 -DCMAKE_BUILD_TYPE=Release
    - make -j 10
    - make install